name: "CI CD Pipeline for Auth Frontend Preprod"

on:
    workflow_dispatch

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: "Setup Node JS"
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: "Check node installation"
              run: |
                node --version
                npm --version

            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: npm install

            - name: "List directory"
              run: ls

            - name: "Run ES Lint"
              run: npm run lint

            - name: "Create project Build"
              run: npm run build